version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=yourpassword # Eğer şifre koymak istersen
      - REDIS_PORT=6379

volumes:
  redis_data:
    driver: local
